name: simple
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pnpm install

    - name: Saludo
      run: echo Hola, mundo!

    - name: Run self-hosted API
      run: npm run dev
